### ISSUE TITLE
build arg not passed

### ISSUE THREAD

**Issue by ldelcano** [EOSC-synergy/SQAaaS#49]
I am creating a service to build a docker image passing a build arg (see attached image)
![image](https://user-images.githubusercontent.com/12271385/148689878-f57ace9a-76ec-44e9-8d8f-52b7923bb2b1.png)
However when I run the pipeline I cannot see the arg taken into account and the docker compose file does not mention it (I am not familiar with this but I assume it should appear somewhere).
```
services:
  scipion-master:
    build:
      context: "./master-image"
      dockerfile: "Dockerfile"
    volumes:
      - type: "bind"
        source: "./"
        target: "/sqaaas-build"
    working_dir: "/sqaaas-build"
    command: "sleep 6000000"
  qc.sty_lovely-xanthic-wolf:
    image: "hadolint/hadolint:latest-alpine"
    volumes:
      - type: "bind"
        source: "./"
        target: "/sqaaas-build"
    working_dir: "/sqaaas-build"
    command: "sleep 6000000"
version: "3.7"
```
Example on https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/ScipionCloud-master.sqaaas/job/devel/3
Am I doing something wrong?
thanks
